#!/usr/bin/env python3
"""
Automated batch processing script for bone fracture X-ray images.
Generated by EnhancedBoneImageProcessor.
"""

import os
import sys
import argparse
from pathlib import Path

# Add the src directory to Python path
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))

from enhanced_preprocessing import EnhancedBoneImageProcessor


def main():
    parser = argparse.ArgumentParser(description='Batch process bone X-ray images')
    parser.add_argument('input_dir', help='Input directory containing images')
    parser.add_argument('output_dir', help='Output directory for processed images')
    parser.add_argument('--enhancement', action='store_true', default=True,
                       help='Apply image enhancement (default: True)')
    parser.add_argument('--workers', type=int, default=None,
                       help='Number of parallel workers')
    parser.add_argument('--config', type=str, default=None,
                       help='Path to configuration file')
    
    args = parser.parse_args()
    
    # Initialize processor
    processor = EnhancedBoneImageProcessor(config_path=args.config)
    
    # Get all image files
    input_path = Path(args.input_dir)
    image_extensions = {'.jpg', '.jpeg', '.png', '.tiff', '.tif', '.bmp'}
    image_paths = [
        str(p) for p in input_path.rglob('*') 
        if p.suffix.lower() in image_extensions
    ]
    
    print(f"Found {len(image_paths)} images to process")
    
    # Process images
    processor.batch_process_images(
        image_paths=image_paths,
        output_dir=args.output_dir,
        apply_enhancement=args.enhancement,
        save_processed=True,
        num_workers=args.workers
    )
    
    # Print statistics
    stats = processor.processing_stats
    print(f"\nProcessing completed:")
    print(f"  Processed: {stats['processed_count']}")
    print(f"  Corrupted: {stats['corrupted_count']}")
    print(f"  Total time: {stats['total_time']:.2f}s")
    print(f"  Enhancement time: {stats['enhancement_time']:.2f}s")


if __name__ == "__main__":
    main()
